export let products = [
  {
    title: "Chocotorta",
    price: 1000,
    stock: 2,
    description: "La mejor chocotorta que probaste!",
    category: "tortas",
    img: "https://res.cloudinary.com/daq80uhh9/image/upload/v1687187749/chocotorta_et1chr.jpg",
  },
  {
    title: "Torta Clasica",
    price: 800,
    stock: 2,
    description: "La mejor opcion para compartir!",
    category: "tortas",
    img: "https://res.cloudinary.com/daq80uhh9/image/upload/v1687187761/torta2_gjyt2s.jpg",
  },
  {
    title: "Inicial Cumpleaños",
    price: 1200,
    stock: 2,
    description: "Ideal para festejar!",
    category: "tortas",
    img: "https://res.cloudinary.com/daq80uhh9/image/upload/v1687187751/tortaletra2_vle0ax.jpg",
  },
  {
    title: "Alfajores",
    price: 200,
    stock: 12,
    description: "Los clasicos!",
    category: "individual",
    img: "https://res.cloudinary.com/daq80uhh9/image/upload/v1687187747/alfajores_ebppml.jpg",
  },
  {
    title: "Alfaoreos",
    price: 300,
    stock: 12,
    description: "Las mejores galles mejoradas!",
    category: "individual",
    img: "https://res.cloudinary.com/daq80uhh9/image/upload/v1687187748/alfaoreo_spatsl.jpg",
  },
  {
    title: "Budines",
    price: 800,
    stock: 2,
    description: "Increible sabor y textura!",
    category: "individual",
    img: "https://res.cloudinary.com/daq80uhh9/image/upload/v1687187748/budines_tbpokj.jpg",
  },
  {
    title: "Chocopaleta",
    price: 500,
    stock: 5,
    description: "Brownie + Chocolate = <3",
    category: "individual",
    img: "https://res.cloudinary.com/daq80uhh9/image/upload/v1687187748/chocopaleta_nnnr6z.jpg",
  },
  {
    title: "Cookies",
    price: 200,
    stock: 12,
    description: "Para disfrutar a la tarde!",
    category: "individual",
    img: "https://res.cloudinary.com/daq80uhh9/image/upload/v1687187753/cookies_vmxznu.jpg",
  },
  {
    title: "Macarons",
    price: 500,
    stock: 12,
    description: "Ideales para regalar!",
    category: "individual",
    img: "https://res.cloudinary.com/daq80uhh9/image/upload/v1687187757/macarons_llnwaf.jpg",
  },
];
